* qDot's Emacs Config

** WARNING

What you see in this repo may not be exactly what I'm using right now.
I sync my emacs files via dropbox, and don't update the repo probably
as often as I should. So, if you want to try to use my full config
repo, and have problems, please feel free to contact me through
github, or IRC (I'm qDot_ on freenode #emacs).

** Description

This repository represents the deep, dark recesses of my soul, better
known as my emacs configuration files.

While it's gone through many different phases and layouts, I now use
an org-babel config. This allows me to use literate programming with
my config and keep it all in a single (rather large) file, in the
hopes that someone other than me might actually understand why I do
what I do. I've tried to provide descriptions to as many things as
possible.

** Package Management

Package management happens by way of package.el using ELPA/MELPA/etc.
All packages that cannot be sync'd via that method are kept as git
submodules in the dev-packages directory.

On first start, MELPA/ELPA packages will sync automatically due to how
I use use-package. However, the packages in dev-packages will need to
be sync'd as submodules and in some cases (cedet, mu) built by hand if
they are to be used.
