* qDot's Emacs Config

** WARNING

What you see in this repo may not be exactly what I'm using right now.
I sync my emacs files via dropbox, and don't update the repo probably
as often as I should. So, if you want to try to use my full config
repo, and have problems, please feel free to contact me through
github, or IRC (I'm qDot_ on freenode #emacs).

** Description

This repository represents the deep, dark recesses of my soul, better
known as my emacs configuration files.

While it's gone through many different phases and layouts, I now use
an org-babel config similar to emacs-starter-kit. This allows me to
use literate programming with my config and keep it all in a single
(rather large) file, in the hopes that someone other than me might
actually understand why I do what I do.

** Package Management via el-get

Package management happens by way of el-get, available at

http://github.com/dimitri/el-get/

My el-get config is in elget-status.el, that will sync all of the
packages I use. Warning: there are a lot.
