import smtplib
import subprocess
import sys
import argparse
import datetime

mail_server = None
mail_sender = None
mail_password = None
receivers = [None]

message = """From: Org Mode Schedule <%s>
To: %s
Subject: Org Mode Schedule - Daily - %s

%s
"""

def main():
  global sender, password
  parser = argparse.ArgumentParser(description='Email org agenda generated by minimal-load files, for use as a cron job to send daily agendas.')
  parser.add_argument('--filename', dest='filename', action='store')
  parser.add_argument('--rec', dest='rec', action='store')

  args = parser.parse_args()

  proc = subprocess.Popen(("emacs -batch -l %s" % args.filename).split(" "), stdout=subprocess.PIPE)
  (body, meh) = proc.communicate()
 
  try:
    smtpObj = smtplib.SMTP(mail_server, 587)
    smtpObj.login(mail_sender, mail_password)
    smtpObj.sendmail(mail_sender, receivers, message % (mail_sender, args.rec, datetime.datetime.now(), body))
    print "Successfully sent email"
  except smtplib.SMTPException:
    print "Error: unable to send email"    

if __name__ == "__main__":
  sys.exit(main())